#include "InteractionDeniedGameplayTags.h"

UE_DEFINE_GAMEPLAY_TAG(TAG_Interaction_Denied_NotFocusable, "Interaction.Denied.NotFocusable")
UE_DEFINE_GAMEPLAY_TAG(TAG_Interaction_Denied_NotInteractable, "Interaction.Denied.NotInteractable")
UE_DEFINE_GAMEPLAY_TAG(TAG_Interaction_Denied_Cooldown_Global, "Interaction.Denied.Cooldown.Global")
UE_DEFINE_GAMEPLAY_TAG(TAG_Interaction_Denied_Cooldown_PerPlayer, "Interaction.Denied.Cooldown.PerPlayer")
UE_DEFINE_GAMEPLAY_TAG(TAG_Interaction_Denied_AlreadyInProgress, "Interaction.Denied.AlreadyInProgress")
UE_DEFINE_GAMEPLAY_TAG(TAG_Interaction_Denied_OutOfRange, "Interaction.Denied.OutOfRange")